FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL 
### Above is the build argument

COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

COPY . .

RUN bun install

RUN bun run db:generate

ENV DATABASE_URL=${DATABASE_URL} 

RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]
