FROM oven/bun:1

WORKDIR /app

COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./app/backend

###ENV DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"

RUN bun install

RUN bun run db:generate

EXPOSE 8080

CMD [ "bun", "run", "start:backend" ]
