FROM oven/bun:1

WORKDIR /app

COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN bun install

RUN bun run db:generate

EXPOSE 8080

CMD [ "bun", "run", "start:backend" ]
