FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL 
### Above is the build argument

COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./apps/web+ ./app/web

###ENV DATABASEURL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"

COPY . .

RUN bun install

RUN bun run db:migrate

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]
